<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Replica.Core\Replica.Core.csproj" />
    <ProjectReference Include="..\..\src\Replica.Mac\Replica.Mac.csproj" />
    <ProjectReference Include="..\..\src\Replica.Mac.Infrastructure\Replica.Mac.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Replica.Storage\Replica.Storage.csproj" />
  </ItemGroup>

</Project>
